### ISSUE TITLE
Make `unexpected-express` with `unexpected` compatible 

### ISSUE THREAD

**Issue by hellboy81** [unexpectedjs/unexpected-express#7] opened 2016-03-04 14:52 UTC
This code throws error:
```js
return expect(app, 'to yield exchange', {
...
}.then(function (context) {
  done() // Has NOT been executed
})
```

```sh
"before each" hook: timeout of 2000ms exceeded

"after each" hook: TODO: You have created a promise that was not returned from the it block
```

The code in tested express  middleware (SUT) seems to be executed correctly

Current library versions:

```js
"unexpected": "~10.9.1",
"unexpected-express": "~8.1.0",
```

**Comment by hellboy81** [comment] 2016-03-07 07:06
The version `10.10.0` is still incompatible with `unexpected-express` (`8.1.0`)

**Comment by papandreou** [comment] 2016-03-07 07:50
Could you paste a complete code sample that includes an `app` that it fails with and the `describe`/`it` stuff? Which test framework are you using?

**Comment by papandreou** [comment] 2016-03-07 08:19
I can reproduce the problem with the unexpected-express test suite run in Jasmine. As of Unexpected 10.9.0 we no longer monkey-patch the `it` function to make Jasmine support promises. Basically it was too risky and they need to implement that themselves. A change like that should have come in a new major version of Unexpected and be documented, so I'm sorry about that.

We still keep the monkey-patching code around so we can run Unexpected's own test suite in Jasmine. Could you try copying https://github.com/unexpectedjs/unexpected/blob/master/test/support/jasmineSetup.js into your project and `require` that at the top of your test file? If that fixes it, you should make some noise here: https://github.com/jasmine/jasmine/pull/1029

**Comment by hellboy81** [comment] 2016-03-07 08:42
> Which test framework are you using?

`"mocha": "~2.4.5"`

>Could you paste a complete code sample that includes an app that it fails with and the describe/it stuff?

```js
var app = express()
app.use(bodyParser.urlencoded({ extended: true }))
// Testing middleware
app.use(sut.grant())

return expect(app, 'to yield exchange', {
     request: {
          method: 'POST',
          headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
          },
          body: '....'
     }
}).then(function (context) {
  done()
})
```
Shoul I provide more info?

**Comment by papandreou** [comment] 2016-03-07 09:07
What about the `it` block around that? And `sut.grant`? I'd have a much better chance of figuring it out if the code you provide runs as-is and reproduces the problem.

**Comment by papandreou** [comment] 2016-03-13 10:41
Just to be completely clear, this is not actionable from my side in its current state. I cannot reproduce the problem with mocha and Unexpected 10.10.5.

I got the test suite to work with node.js 4 and 5 and enabled those on Travis, and it passes with all versions: https://travis-ci.org/unexpectedjs/unexpected-express/builds/115649443

You'll have to provide a complete standalone test file that fails and tell me exactly which version of node.js, mocha etc. you're using.

**Comment by papandreou** [comment] 2016-03-31 12:12
Closing for now, please reopen if you can come up with a complete example that fails with Unexpected 10.11.0 and unexpected-express 8.2.0.

**Closed by papandreou** 2016-03-31 12:12 UTC
